In [1]:
import pandas as pd
import numpy as np
np.set_printoptions(suppress=True)

In [38]:
dat1 = pd.read_csv('FoodRatings_all_same_5_4_3.csv')
dat1


Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         4            4     4      0      0   
5     F        0       0       0         4            4     4      0      0   
6     G        0       0       0         4            4     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      3      3   
9     J        0       0       0         0            0     0      3      3   
10    K        0       0       0         0            0     0      3      3   
11    L        0       0       0         0            0     0      3      3   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         3  
9         3  
10        3  
11        3

In [39]:
dat = dat1.drop(['Name'], axis=1)

In [40]:
#Let'se use the SVD function from np.linalg library
U, s, VT = np.linalg.svd(dat, full_matrices=False)

In [41]:
U 

array([[-0.5       ,  0.        ,  0.        ,  0.8660254 ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.5       ,  0.        ,  0.        , -0.28867513,  0.81649658,
        -0.        ,  0.        ,  0.        ,  0.        ],
       [-0.5       ,  0.        ,  0.        , -0.28867513, -0.40824829,
        -0.1767767 ,  0.35355339,  0.35355339,  0.35355339],
       [-0.5       ,  0.        ,  0.        , -0.28867513, -0.40824829,
         0.1767767 , -0.35355339, -0.35355339, -0.35355339],
       [ 0.        , -0.5       ,  0.        ,  0.        ,  0.        ,
         0.125     , -0.25      , -0.25      ,  0.75      ],
       [ 0.        , -0.5       ,  0.        ,  0.        ,  0.        ,
         0.125     , -0.25      ,  0.75      , -0.25      ],
       [ 0.        , -0.5       ,  0.        ,  0.        ,  0.        ,
        -0.375     , -0.25      , -0.25      , -0.25      ],
       [ 0.        , -0.5       ,  0.        ,  0.        ,  0

In [42]:
s

array([17.32050808, 13.85640646, 10.39230485,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [43]:
VT

array([[-0.57735027, -0.57735027, -0.57735027,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.        , -0.        , -0.57735027, -0.57735027,
        -0.57735027,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.        , -0.        ,  0.        ,  0.        ,
         0.        , -0.57735027, -0.57735027, -0.57735027],
       [ 0.81649658, -0.40824829, -0.40824829,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.        ,  0.70710678, -0.70710678, -0.        , -0.        ,
        -0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.81649658, -0.40824829, -0.40824829],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0

In [32]:
U.shape

(12, 9)

In [33]:
VT.shape


(9, 9)

In [34]:
np.diag(s[:3])

array([[17.32050808,  0.        ,  0.        ],
       [ 0.        , 17.32050808,  0.        ],
       [ 0.        ,  0.        , 17.32050808]])

In [35]:
VT_DF = pd.DataFrame(VT)
VT_DF

0         1         2         3         4         5         6  \
0 -0.000000 -0.000000 -0.000000 -0.577350 -0.577350 -0.577350  0.000000   
1 -0.000000 -0.000000 -0.000000  0.000000  0.000000  0.000000 -0.577350   
2 -0.577350 -0.577350 -0.577350  0.000000  0.000000  0.000000  0.000000   
3  0.816497 -0.408248 -0.408248  0.000000  0.000000  0.000000  0.000000   
4 -0.000000  0.707107 -0.707107 -0.000000 -0.000000 -0.000000  0.000000   
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.000000  0.816497 -0.408248 -0.408248  0.000000   
7  0.000000  0.000000  0.000000  0.000000 -0.707107  0.707107  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.816497   

          7         8  
0  0.000000  0.000000  
1 -0.577350 -0.577350  
2  0.000000  0.000000  
3  0.000000  0.000000  
4  0.000000  0.000000  
5 -0.707107  0.707107  
6  0.000000  0.000000  
7  0.000000  0.000000  
8 -0.408248 -0.408248